/* (SYNC) */

export const ADD_CONTACT = 'ADD_CONTACT';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';
export const CHANGE_CONTACT = 'CHANGE_CONTACT';

/* (ASYNC) */
export const SAVE_CLIENTE_INIT = 'SAVE_CLIENTE_INIT';
export const SAVE_CLIENTE_SUCCESS = 'SAVE_CLIENTE_SUCCESS';
export const SAVE_CLIENTE_FAILURE = 'SAVE_CLIENTE_FAILURE';
