/* (SYNC) */

export const ADD_CONTACT = 'ADD_CONTACT';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';
export const CHANGE_CONTACT = 'CHANGE_CONTACT';
export const RESET_STATE = 'RESET_STATE';

/* (ASYNC) */
export const UPDATE_CLIENTE_INIT = 'UPDATE_CLIENTE_INIT';
export const UPDATE_CLIENTE_SUCCESS = 'UPDATE_CLIENTE_SUCCESS';
export const UPDATE_CLIENTE_FAILURE = 'UPDATE_CLIENTE_FAILURE';
