/* (SYNC) */

/* (ASYNC) */
export const FETCH_CLIENTS_AU_INIT = 'FETCH_CLIENTS_AU_INIT';
export const FETCH_CLIENTS_AU_SUCCESS = 'FETCH_CLIENTS_AU_SUCCESS';
export const FETCH_CLIENTS_AU_FAILURE = 'FETCH_CLIENTS_AU_FAILURE';
